insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1000, 'San Angel', 'Alvaro Obregon', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1010, 'Los Alpes', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1020, 'Guadalupe Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1028, 'Secretaria de Contraloría y Desarrollo Administrativo', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1029, 'INFONAVIT', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1030, 'Florida;Axotla', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1040, 'Campestre', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1048, 'Las Águilas', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1049, 'Tlacopac', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1060, 'Altavista;San Angel Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1001, 'San Angel', 'Alvaro Obregon', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1012, 'Los Alpes', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1023, 'Guadalupe Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1128, 'Secretaria de Contraloría y Desarrollo Administrativo', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(11029, 'INFONAVIT', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(12030, 'Florida;Axotla', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10340, 'Campestre', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10458, 'Las Águilas', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10494, 'Tlacopac', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(19060, 'Altavista;San Angel Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(107700, 'San Angel', 'Alvaro Obregon', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10910, 'Los Alpes', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10920, 'Guadalupe Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10928, 'Secretaria de Contraloría y Desarrollo Administrativo', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10929, 'INFONAVIT', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(19030, 'Florida;Axotla', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10440, 'Campestre', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(145048, 'Las Águilas', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(104549, 'Tlacopac', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(104560, 'Altavista;San Angel Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(104500, 'San Angel', 'Alvaro Obregon', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(107810, 'Los Alpes', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(107820, 'Guadalupe Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(107828, 'Secretaria de Contraloría y Desarrollo Administrativo', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(100029, 'INFONAVIT', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(10030, 'Florida;Axotla', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(18040, 'Campestre', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(107748, 'Las Águilas', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(1077749, 'Tlacopac', 'Álvaro Obregón', 'Distrito Federal');
insert into codigospostales (codigoPostal, colonia, municipio, estado) values(107860, 'Altavista;San Angel Inn', 'Álvaro Obregón', 'Distrito Federal');
insert into foo (id, name) values(666, 'bob');
